apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: hooni
          image: hooni:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-storage
              mountPath: /images
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: pvc0001

