apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: windows-share-pv
  storageClassName: ""
