apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs-pvc
  namespace: hooni  # <--- Target your specific workspace here
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Gi
