apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hooni-images-pvc
spec:
  storageClassName: ""
  volumeName: hooni-images-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
