mysql:
  image: mysql:5.7
  database: mydb
  storage: 50Gi
  backupPvc: mysql-backup-pvc
  backupStorage: 2Gi
  serviceName: mysql
  restore:
    enabled: false

redis:
  image: redis:latest
  storage: 10Gi

hooniApp:
  image: localhost:32000/hooni-app:1.0
  imagePullPolicy: IfNotPresent
  replicaCount: 3
  profile: docker
  dbUser: root
  dbHost: mysql
  dbPort: 3306
  dbName: mydb
  redisHost: redis
  redisPort: 6379
  redisTimeout: 2000
  redisSsl: false
  servicePort: 80
  serverPort: 8080
  hostname: hoo-ni.com
  tlsSecretName: "ionos-ssl-secret"

hooniImages:
  hostPath: /storage/hooniImages
  storage: 10Gi
  imagesPath: "/storage/hooniImages/"

nfs:
  server: "192.168.1.217"
  share: "/storage"
  storageSize: "100Gi"
  imagesPath: "/storage/hooniImages/"
