apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hooni-app
  namespace: hooni
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.hooniApp.hostname | quote | default "hoo-ni.com" }}
        - "www.{{ .Values.hooniApp.hostname | default "hoo-ni.com" }}" # 👈 ADD THIS VARIANT
      secretName: ionos-ssl-secret
  rules:
    - host: {{ .Values.hooniApp.hostname | default "hoo-ni.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hooni-app
                port:
                  number: {{ .Values.hooniApp.servicePort }}
    - host: "www.{{ .Values.hooniApp.hostname | default "hoo-ni.com" }}" # 👈 ADD THIS ENTIRE BLOCK
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hooni-app
                port:
                  number: {{ .Values.hooniApp.servicePort }}
