apiVersion: v1
kind: PersistentVolume
metadata:
  name: hooni-images-pv
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.hooniImages.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hooniImages.hostPath }}"
