apiVersion: v1
kind: Service
metadata:
  name: hooni-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.hooniApp.servicePort }}
      targetPort: {{ .Values.hooniApp.serverPort }}
  selector:
    app: hooni-app
