apiVersion: v1
kind: Service
metadata:
  name: hooni-app
spec:
  type: NodePort
  ports:
    - port: {{ .Values.hooniApp.servicePort }}
      nodePort: {{ .Values.hooniApp.nodePort }}
  selector:
    app: hooni-app
