apiVersion: v1
kind: PersistentVolume
metadata:
  name: hooni-static-pv
spec:
  capacity:
    storage: {{ .Values.nfs.storageSize | default "100Gi" }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain   # Keeps data safe if PVC is deleted
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: hooni-static-volume-id-unique
    volumeAttributes:
      server: {{ .Values.nfs.server | default "192.168.1.217" }}
      share: {{ .Values.nfs.imagesPath | default "/storage/hooniImages" }}       # 👈 Hardcoded straight to your image directory!
