apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  volumeName: hooni-static-pv             # 👈 Critical: Binds directly to the static PV
  resources:
    requests:
      storage: {{ .Values.nfs.storageSize | default "100Gi" }}
