apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs-pvc    # Fixed static name (No namespace field here!)
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi # Matches the StorageClass name above
  resources:
    requests:
      storage: {{ .Values.nfs.storageSize | default "100Gi" }}
